// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"

	model "github.com/enbility/spine-go/model"
)

// UCEVCEMInterface is an autogenerated mock type for the UCEVCEMInterface type
type UCEVCEMInterface struct {
	mock.Mock
}

type UCEVCEMInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *UCEVCEMInterface) EXPECT() *UCEVCEMInterface_Expecter {
	return &UCEVCEMInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function with given fields:
func (_m *UCEVCEMInterface) AddFeatures() {
	_m.Called()
}

// UCEVCEMInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type UCEVCEMInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *UCEVCEMInterface_Expecter) AddFeatures() *UCEVCEMInterface_AddFeatures_Call {
	return &UCEVCEMInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *UCEVCEMInterface_AddFeatures_Call) Run(run func()) *UCEVCEMInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCEVCEMInterface_AddFeatures_Call) Return() *UCEVCEMInterface_AddFeatures_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCEVCEMInterface_AddFeatures_Call) RunAndReturn(run func()) *UCEVCEMInterface_AddFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddUseCase provides a mock function with given fields:
func (_m *UCEVCEMInterface) AddUseCase() {
	_m.Called()
}

// UCEVCEMInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type UCEVCEMInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *UCEVCEMInterface_Expecter) AddUseCase() *UCEVCEMInterface_AddUseCase_Call {
	return &UCEVCEMInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *UCEVCEMInterface_AddUseCase_Call) Run(run func()) *UCEVCEMInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCEVCEMInterface_AddUseCase_Call) Return() *UCEVCEMInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCEVCEMInterface_AddUseCase_Call) RunAndReturn(run func()) *UCEVCEMInterface_AddUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentPerPhase provides a mock function with given fields: entity
func (_m *UCEVCEMInterface) CurrentPerPhase(entity api.EntityRemoteInterface) ([]float64, error) {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for CurrentPerPhase")
	}

	var r0 []float64
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) ([]float64, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) []float64); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCEVCEMInterface_CurrentPerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentPerPhase'
type UCEVCEMInterface_CurrentPerPhase_Call struct {
	*mock.Call
}

// CurrentPerPhase is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *UCEVCEMInterface_Expecter) CurrentPerPhase(entity interface{}) *UCEVCEMInterface_CurrentPerPhase_Call {
	return &UCEVCEMInterface_CurrentPerPhase_Call{Call: _e.mock.On("CurrentPerPhase", entity)}
}

func (_c *UCEVCEMInterface_CurrentPerPhase_Call) Run(run func(entity api.EntityRemoteInterface)) *UCEVCEMInterface_CurrentPerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCEVCEMInterface_CurrentPerPhase_Call) Return(_a0 []float64, _a1 error) *UCEVCEMInterface_CurrentPerPhase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCEVCEMInterface_CurrentPerPhase_Call) RunAndReturn(run func(api.EntityRemoteInterface) ([]float64, error)) *UCEVCEMInterface_CurrentPerPhase_Call {
	_c.Call.Return(run)
	return _c
}

// EnergyCharged provides a mock function with given fields: entity
func (_m *UCEVCEMInterface) EnergyCharged(entity api.EntityRemoteInterface) (float64, error) {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for EnergyCharged")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (float64, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) float64); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCEVCEMInterface_EnergyCharged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnergyCharged'
type UCEVCEMInterface_EnergyCharged_Call struct {
	*mock.Call
}

// EnergyCharged is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *UCEVCEMInterface_Expecter) EnergyCharged(entity interface{}) *UCEVCEMInterface_EnergyCharged_Call {
	return &UCEVCEMInterface_EnergyCharged_Call{Call: _e.mock.On("EnergyCharged", entity)}
}

func (_c *UCEVCEMInterface_EnergyCharged_Call) Run(run func(entity api.EntityRemoteInterface)) *UCEVCEMInterface_EnergyCharged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCEVCEMInterface_EnergyCharged_Call) Return(_a0 float64, _a1 error) *UCEVCEMInterface_EnergyCharged_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCEVCEMInterface_EnergyCharged_Call) RunAndReturn(run func(api.EntityRemoteInterface) (float64, error)) *UCEVCEMInterface_EnergyCharged_Call {
	_c.Call.Return(run)
	return _c
}

// IsUseCaseSupported provides a mock function with given fields: remoteEntity
func (_m *UCEVCEMInterface) IsUseCaseSupported(remoteEntity api.EntityRemoteInterface) (bool, error) {
	ret := _m.Called(remoteEntity)

	if len(ret) == 0 {
		panic("no return value specified for IsUseCaseSupported")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (bool, error)); ok {
		return rf(remoteEntity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) bool); ok {
		r0 = rf(remoteEntity)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(remoteEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCEVCEMInterface_IsUseCaseSupported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUseCaseSupported'
type UCEVCEMInterface_IsUseCaseSupported_Call struct {
	*mock.Call
}

// IsUseCaseSupported is a helper method to define mock.On call
//   - remoteEntity api.EntityRemoteInterface
func (_e *UCEVCEMInterface_Expecter) IsUseCaseSupported(remoteEntity interface{}) *UCEVCEMInterface_IsUseCaseSupported_Call {
	return &UCEVCEMInterface_IsUseCaseSupported_Call{Call: _e.mock.On("IsUseCaseSupported", remoteEntity)}
}

func (_c *UCEVCEMInterface_IsUseCaseSupported_Call) Run(run func(remoteEntity api.EntityRemoteInterface)) *UCEVCEMInterface_IsUseCaseSupported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCEVCEMInterface_IsUseCaseSupported_Call) Return(_a0 bool, _a1 error) *UCEVCEMInterface_IsUseCaseSupported_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCEVCEMInterface_IsUseCaseSupported_Call) RunAndReturn(run func(api.EntityRemoteInterface) (bool, error)) *UCEVCEMInterface_IsUseCaseSupported_Call {
	_c.Call.Return(run)
	return _c
}

// PhasesConnected provides a mock function with given fields: entity
func (_m *UCEVCEMInterface) PhasesConnected(entity api.EntityRemoteInterface) (uint, error) {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for PhasesConnected")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (uint, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) uint); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCEVCEMInterface_PhasesConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PhasesConnected'
type UCEVCEMInterface_PhasesConnected_Call struct {
	*mock.Call
}

// PhasesConnected is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *UCEVCEMInterface_Expecter) PhasesConnected(entity interface{}) *UCEVCEMInterface_PhasesConnected_Call {
	return &UCEVCEMInterface_PhasesConnected_Call{Call: _e.mock.On("PhasesConnected", entity)}
}

func (_c *UCEVCEMInterface_PhasesConnected_Call) Run(run func(entity api.EntityRemoteInterface)) *UCEVCEMInterface_PhasesConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCEVCEMInterface_PhasesConnected_Call) Return(_a0 uint, _a1 error) *UCEVCEMInterface_PhasesConnected_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCEVCEMInterface_PhasesConnected_Call) RunAndReturn(run func(api.EntityRemoteInterface) (uint, error)) *UCEVCEMInterface_PhasesConnected_Call {
	_c.Call.Return(run)
	return _c
}

// PowerPerPhase provides a mock function with given fields: entity
func (_m *UCEVCEMInterface) PowerPerPhase(entity api.EntityRemoteInterface) ([]float64, error) {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for PowerPerPhase")
	}

	var r0 []float64
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) ([]float64, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) []float64); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCEVCEMInterface_PowerPerPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PowerPerPhase'
type UCEVCEMInterface_PowerPerPhase_Call struct {
	*mock.Call
}

// PowerPerPhase is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *UCEVCEMInterface_Expecter) PowerPerPhase(entity interface{}) *UCEVCEMInterface_PowerPerPhase_Call {
	return &UCEVCEMInterface_PowerPerPhase_Call{Call: _e.mock.On("PowerPerPhase", entity)}
}

func (_c *UCEVCEMInterface_PowerPerPhase_Call) Run(run func(entity api.EntityRemoteInterface)) *UCEVCEMInterface_PowerPerPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCEVCEMInterface_PowerPerPhase_Call) Return(_a0 []float64, _a1 error) *UCEVCEMInterface_PowerPerPhase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCEVCEMInterface_PowerPerPhase_Call) RunAndReturn(run func(api.EntityRemoteInterface) ([]float64, error)) *UCEVCEMInterface_PowerPerPhase_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function with given fields: available
func (_m *UCEVCEMInterface) UpdateUseCaseAvailability(available bool) {
	_m.Called(available)
}

// UCEVCEMInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type UCEVCEMInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *UCEVCEMInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *UCEVCEMInterface_UpdateUseCaseAvailability_Call {
	return &UCEVCEMInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *UCEVCEMInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *UCEVCEMInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *UCEVCEMInterface_UpdateUseCaseAvailability_Call) Return() *UCEVCEMInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCEVCEMInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(bool)) *UCEVCEMInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// UseCaseName provides a mock function with given fields:
func (_m *UCEVCEMInterface) UseCaseName() model.UseCaseNameType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UseCaseName")
	}

	var r0 model.UseCaseNameType
	if rf, ok := ret.Get(0).(func() model.UseCaseNameType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.UseCaseNameType)
	}

	return r0
}

// UCEVCEMInterface_UseCaseName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseCaseName'
type UCEVCEMInterface_UseCaseName_Call struct {
	*mock.Call
}

// UseCaseName is a helper method to define mock.On call
func (_e *UCEVCEMInterface_Expecter) UseCaseName() *UCEVCEMInterface_UseCaseName_Call {
	return &UCEVCEMInterface_UseCaseName_Call{Call: _e.mock.On("UseCaseName")}
}

func (_c *UCEVCEMInterface_UseCaseName_Call) Run(run func()) *UCEVCEMInterface_UseCaseName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCEVCEMInterface_UseCaseName_Call) Return(_a0 model.UseCaseNameType) *UCEVCEMInterface_UseCaseName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCEVCEMInterface_UseCaseName_Call) RunAndReturn(run func() model.UseCaseNameType) *UCEVCEMInterface_UseCaseName_Call {
	_c.Call.Return(run)
	return _c
}

// NewUCEVCEMInterface creates a new instance of UCEVCEMInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUCEVCEMInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UCEVCEMInterface {
	mock := &UCEVCEMInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
