// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"

	model "github.com/enbility/spine-go/model"
)

// UCEVSOCInterface is an autogenerated mock type for the UCEVSOCInterface type
type UCEVSOCInterface struct {
	mock.Mock
}

type UCEVSOCInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *UCEVSOCInterface) EXPECT() *UCEVSOCInterface_Expecter {
	return &UCEVSOCInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function with given fields:
func (_m *UCEVSOCInterface) AddFeatures() {
	_m.Called()
}

// UCEVSOCInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type UCEVSOCInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *UCEVSOCInterface_Expecter) AddFeatures() *UCEVSOCInterface_AddFeatures_Call {
	return &UCEVSOCInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *UCEVSOCInterface_AddFeatures_Call) Run(run func()) *UCEVSOCInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCEVSOCInterface_AddFeatures_Call) Return() *UCEVSOCInterface_AddFeatures_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCEVSOCInterface_AddFeatures_Call) RunAndReturn(run func()) *UCEVSOCInterface_AddFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddUseCase provides a mock function with given fields:
func (_m *UCEVSOCInterface) AddUseCase() {
	_m.Called()
}

// UCEVSOCInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type UCEVSOCInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *UCEVSOCInterface_Expecter) AddUseCase() *UCEVSOCInterface_AddUseCase_Call {
	return &UCEVSOCInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *UCEVSOCInterface_AddUseCase_Call) Run(run func()) *UCEVSOCInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCEVSOCInterface_AddUseCase_Call) Return() *UCEVSOCInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCEVSOCInterface_AddUseCase_Call) RunAndReturn(run func()) *UCEVSOCInterface_AddUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// IsUseCaseSupported provides a mock function with given fields: remoteEntity
func (_m *UCEVSOCInterface) IsUseCaseSupported(remoteEntity api.EntityRemoteInterface) (bool, error) {
	ret := _m.Called(remoteEntity)

	if len(ret) == 0 {
		panic("no return value specified for IsUseCaseSupported")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (bool, error)); ok {
		return rf(remoteEntity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) bool); ok {
		r0 = rf(remoteEntity)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(remoteEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCEVSOCInterface_IsUseCaseSupported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUseCaseSupported'
type UCEVSOCInterface_IsUseCaseSupported_Call struct {
	*mock.Call
}

// IsUseCaseSupported is a helper method to define mock.On call
//   - remoteEntity api.EntityRemoteInterface
func (_e *UCEVSOCInterface_Expecter) IsUseCaseSupported(remoteEntity interface{}) *UCEVSOCInterface_IsUseCaseSupported_Call {
	return &UCEVSOCInterface_IsUseCaseSupported_Call{Call: _e.mock.On("IsUseCaseSupported", remoteEntity)}
}

func (_c *UCEVSOCInterface_IsUseCaseSupported_Call) Run(run func(remoteEntity api.EntityRemoteInterface)) *UCEVSOCInterface_IsUseCaseSupported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCEVSOCInterface_IsUseCaseSupported_Call) Return(_a0 bool, _a1 error) *UCEVSOCInterface_IsUseCaseSupported_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCEVSOCInterface_IsUseCaseSupported_Call) RunAndReturn(run func(api.EntityRemoteInterface) (bool, error)) *UCEVSOCInterface_IsUseCaseSupported_Call {
	_c.Call.Return(run)
	return _c
}

// StateOfCharge provides a mock function with given fields: entity
func (_m *UCEVSOCInterface) StateOfCharge(entity api.EntityRemoteInterface) (float64, error) {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for StateOfCharge")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (float64, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) float64); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCEVSOCInterface_StateOfCharge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StateOfCharge'
type UCEVSOCInterface_StateOfCharge_Call struct {
	*mock.Call
}

// StateOfCharge is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *UCEVSOCInterface_Expecter) StateOfCharge(entity interface{}) *UCEVSOCInterface_StateOfCharge_Call {
	return &UCEVSOCInterface_StateOfCharge_Call{Call: _e.mock.On("StateOfCharge", entity)}
}

func (_c *UCEVSOCInterface_StateOfCharge_Call) Run(run func(entity api.EntityRemoteInterface)) *UCEVSOCInterface_StateOfCharge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCEVSOCInterface_StateOfCharge_Call) Return(_a0 float64, _a1 error) *UCEVSOCInterface_StateOfCharge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCEVSOCInterface_StateOfCharge_Call) RunAndReturn(run func(api.EntityRemoteInterface) (float64, error)) *UCEVSOCInterface_StateOfCharge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function with given fields: available
func (_m *UCEVSOCInterface) UpdateUseCaseAvailability(available bool) {
	_m.Called(available)
}

// UCEVSOCInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type UCEVSOCInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *UCEVSOCInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *UCEVSOCInterface_UpdateUseCaseAvailability_Call {
	return &UCEVSOCInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *UCEVSOCInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *UCEVSOCInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *UCEVSOCInterface_UpdateUseCaseAvailability_Call) Return() *UCEVSOCInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCEVSOCInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(bool)) *UCEVSOCInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// UseCaseName provides a mock function with given fields:
func (_m *UCEVSOCInterface) UseCaseName() model.UseCaseNameType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UseCaseName")
	}

	var r0 model.UseCaseNameType
	if rf, ok := ret.Get(0).(func() model.UseCaseNameType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.UseCaseNameType)
	}

	return r0
}

// UCEVSOCInterface_UseCaseName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseCaseName'
type UCEVSOCInterface_UseCaseName_Call struct {
	*mock.Call
}

// UseCaseName is a helper method to define mock.On call
func (_e *UCEVSOCInterface_Expecter) UseCaseName() *UCEVSOCInterface_UseCaseName_Call {
	return &UCEVSOCInterface_UseCaseName_Call{Call: _e.mock.On("UseCaseName")}
}

func (_c *UCEVSOCInterface_UseCaseName_Call) Run(run func()) *UCEVSOCInterface_UseCaseName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCEVSOCInterface_UseCaseName_Call) Return(_a0 model.UseCaseNameType) *UCEVSOCInterface_UseCaseName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCEVSOCInterface_UseCaseName_Call) RunAndReturn(run func() model.UseCaseNameType) *UCEVSOCInterface_UseCaseName_Call {
	_c.Call.Return(run)
	return _c
}

// NewUCEVSOCInterface creates a new instance of UCEVSOCInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUCEVSOCInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UCEVSOCInterface {
	mock := &UCEVSOCInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
