// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/cemd/api"
	mock "github.com/stretchr/testify/mock"

	model "github.com/enbility/spine-go/model"

	spine_goapi "github.com/enbility/spine-go/api"

	time "time"
)

// UCLPCServerInterface is an autogenerated mock type for the UCLPCServerInterface type
type UCLPCServerInterface struct {
	mock.Mock
}

type UCLPCServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *UCLPCServerInterface) EXPECT() *UCLPCServerInterface_Expecter {
	return &UCLPCServerInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function with given fields:
func (_m *UCLPCServerInterface) AddFeatures() {
	_m.Called()
}

// UCLPCServerInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type UCLPCServerInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *UCLPCServerInterface_Expecter) AddFeatures() *UCLPCServerInterface_AddFeatures_Call {
	return &UCLPCServerInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *UCLPCServerInterface_AddFeatures_Call) Run(run func()) *UCLPCServerInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCLPCServerInterface_AddFeatures_Call) Return() *UCLPCServerInterface_AddFeatures_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCLPCServerInterface_AddFeatures_Call) RunAndReturn(run func()) *UCLPCServerInterface_AddFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddUseCase provides a mock function with given fields:
func (_m *UCLPCServerInterface) AddUseCase() {
	_m.Called()
}

// UCLPCServerInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type UCLPCServerInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *UCLPCServerInterface_Expecter) AddUseCase() *UCLPCServerInterface_AddUseCase_Call {
	return &UCLPCServerInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *UCLPCServerInterface_AddUseCase_Call) Run(run func()) *UCLPCServerInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCLPCServerInterface_AddUseCase_Call) Return() *UCLPCServerInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCLPCServerInterface_AddUseCase_Call) RunAndReturn(run func()) *UCLPCServerInterface_AddUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumptionLimit provides a mock function with given fields:
func (_m *UCLPCServerInterface) ConsumptionLimit() (api.LoadLimit, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConsumptionLimit")
	}

	var r0 api.LoadLimit
	var r1 error
	if rf, ok := ret.Get(0).(func() (api.LoadLimit, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() api.LoadLimit); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(api.LoadLimit)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCLPCServerInterface_ConsumptionLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumptionLimit'
type UCLPCServerInterface_ConsumptionLimit_Call struct {
	*mock.Call
}

// ConsumptionLimit is a helper method to define mock.On call
func (_e *UCLPCServerInterface_Expecter) ConsumptionLimit() *UCLPCServerInterface_ConsumptionLimit_Call {
	return &UCLPCServerInterface_ConsumptionLimit_Call{Call: _e.mock.On("ConsumptionLimit")}
}

func (_c *UCLPCServerInterface_ConsumptionLimit_Call) Run(run func()) *UCLPCServerInterface_ConsumptionLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCLPCServerInterface_ConsumptionLimit_Call) Return(_a0 api.LoadLimit, _a1 error) *UCLPCServerInterface_ConsumptionLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCLPCServerInterface_ConsumptionLimit_Call) RunAndReturn(run func() (api.LoadLimit, error)) *UCLPCServerInterface_ConsumptionLimit_Call {
	_c.Call.Return(run)
	return _c
}

// ContractualConsumptionNominalMax provides a mock function with given fields:
func (_m *UCLPCServerInterface) ContractualConsumptionNominalMax() (float64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContractualConsumptionNominalMax")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func() (float64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCLPCServerInterface_ContractualConsumptionNominalMax_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContractualConsumptionNominalMax'
type UCLPCServerInterface_ContractualConsumptionNominalMax_Call struct {
	*mock.Call
}

// ContractualConsumptionNominalMax is a helper method to define mock.On call
func (_e *UCLPCServerInterface_Expecter) ContractualConsumptionNominalMax() *UCLPCServerInterface_ContractualConsumptionNominalMax_Call {
	return &UCLPCServerInterface_ContractualConsumptionNominalMax_Call{Call: _e.mock.On("ContractualConsumptionNominalMax")}
}

func (_c *UCLPCServerInterface_ContractualConsumptionNominalMax_Call) Run(run func()) *UCLPCServerInterface_ContractualConsumptionNominalMax_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCLPCServerInterface_ContractualConsumptionNominalMax_Call) Return(_a0 float64, _a1 error) *UCLPCServerInterface_ContractualConsumptionNominalMax_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCLPCServerInterface_ContractualConsumptionNominalMax_Call) RunAndReturn(run func() (float64, error)) *UCLPCServerInterface_ContractualConsumptionNominalMax_Call {
	_c.Call.Return(run)
	return _c
}

// FailsafeConsumptionActivePowerLimit provides a mock function with given fields:
func (_m *UCLPCServerInterface) FailsafeConsumptionActivePowerLimit() (float64, bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FailsafeConsumptionActivePowerLimit")
	}

	var r0 float64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func() (float64, bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailsafeConsumptionActivePowerLimit'
type UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call struct {
	*mock.Call
}

// FailsafeConsumptionActivePowerLimit is a helper method to define mock.On call
func (_e *UCLPCServerInterface_Expecter) FailsafeConsumptionActivePowerLimit() *UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call {
	return &UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call{Call: _e.mock.On("FailsafeConsumptionActivePowerLimit")}
}

func (_c *UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call) Run(run func()) *UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call) Return(value float64, isChangeable bool, resultErr error) *UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call {
	_c.Call.Return(value, isChangeable, resultErr)
	return _c
}

func (_c *UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call) RunAndReturn(run func() (float64, bool, error)) *UCLPCServerInterface_FailsafeConsumptionActivePowerLimit_Call {
	_c.Call.Return(run)
	return _c
}

// FailsafeDurationMinimum provides a mock function with given fields:
func (_m *UCLPCServerInterface) FailsafeDurationMinimum() (time.Duration, bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FailsafeDurationMinimum")
	}

	var r0 time.Duration
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func() (time.Duration, bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UCLPCServerInterface_FailsafeDurationMinimum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailsafeDurationMinimum'
type UCLPCServerInterface_FailsafeDurationMinimum_Call struct {
	*mock.Call
}

// FailsafeDurationMinimum is a helper method to define mock.On call
func (_e *UCLPCServerInterface_Expecter) FailsafeDurationMinimum() *UCLPCServerInterface_FailsafeDurationMinimum_Call {
	return &UCLPCServerInterface_FailsafeDurationMinimum_Call{Call: _e.mock.On("FailsafeDurationMinimum")}
}

func (_c *UCLPCServerInterface_FailsafeDurationMinimum_Call) Run(run func()) *UCLPCServerInterface_FailsafeDurationMinimum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCLPCServerInterface_FailsafeDurationMinimum_Call) Return(duration time.Duration, isChangeable bool, resultErr error) *UCLPCServerInterface_FailsafeDurationMinimum_Call {
	_c.Call.Return(duration, isChangeable, resultErr)
	return _c
}

func (_c *UCLPCServerInterface_FailsafeDurationMinimum_Call) RunAndReturn(run func() (time.Duration, bool, error)) *UCLPCServerInterface_FailsafeDurationMinimum_Call {
	_c.Call.Return(run)
	return _c
}

// IsUseCaseSupported provides a mock function with given fields: remoteEntity
func (_m *UCLPCServerInterface) IsUseCaseSupported(remoteEntity spine_goapi.EntityRemoteInterface) (bool, error) {
	ret := _m.Called(remoteEntity)

	if len(ret) == 0 {
		panic("no return value specified for IsUseCaseSupported")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(spine_goapi.EntityRemoteInterface) (bool, error)); ok {
		return rf(remoteEntity)
	}
	if rf, ok := ret.Get(0).(func(spine_goapi.EntityRemoteInterface) bool); ok {
		r0 = rf(remoteEntity)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(spine_goapi.EntityRemoteInterface) error); ok {
		r1 = rf(remoteEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCLPCServerInterface_IsUseCaseSupported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUseCaseSupported'
type UCLPCServerInterface_IsUseCaseSupported_Call struct {
	*mock.Call
}

// IsUseCaseSupported is a helper method to define mock.On call
//   - remoteEntity spine_goapi.EntityRemoteInterface
func (_e *UCLPCServerInterface_Expecter) IsUseCaseSupported(remoteEntity interface{}) *UCLPCServerInterface_IsUseCaseSupported_Call {
	return &UCLPCServerInterface_IsUseCaseSupported_Call{Call: _e.mock.On("IsUseCaseSupported", remoteEntity)}
}

func (_c *UCLPCServerInterface_IsUseCaseSupported_Call) Run(run func(remoteEntity spine_goapi.EntityRemoteInterface)) *UCLPCServerInterface_IsUseCaseSupported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(spine_goapi.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCLPCServerInterface_IsUseCaseSupported_Call) Return(_a0 bool, _a1 error) *UCLPCServerInterface_IsUseCaseSupported_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCLPCServerInterface_IsUseCaseSupported_Call) RunAndReturn(run func(spine_goapi.EntityRemoteInterface) (bool, error)) *UCLPCServerInterface_IsUseCaseSupported_Call {
	_c.Call.Return(run)
	return _c
}

// SetConsumptionLimit provides a mock function with given fields: limit
func (_m *UCLPCServerInterface) SetConsumptionLimit(limit api.LoadLimit) error {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for SetConsumptionLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(api.LoadLimit) error); ok {
		r0 = rf(limit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UCLPCServerInterface_SetConsumptionLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConsumptionLimit'
type UCLPCServerInterface_SetConsumptionLimit_Call struct {
	*mock.Call
}

// SetConsumptionLimit is a helper method to define mock.On call
//   - limit api.LoadLimit
func (_e *UCLPCServerInterface_Expecter) SetConsumptionLimit(limit interface{}) *UCLPCServerInterface_SetConsumptionLimit_Call {
	return &UCLPCServerInterface_SetConsumptionLimit_Call{Call: _e.mock.On("SetConsumptionLimit", limit)}
}

func (_c *UCLPCServerInterface_SetConsumptionLimit_Call) Run(run func(limit api.LoadLimit)) *UCLPCServerInterface_SetConsumptionLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.LoadLimit))
	})
	return _c
}

func (_c *UCLPCServerInterface_SetConsumptionLimit_Call) Return(resultErr error) *UCLPCServerInterface_SetConsumptionLimit_Call {
	_c.Call.Return(resultErr)
	return _c
}

func (_c *UCLPCServerInterface_SetConsumptionLimit_Call) RunAndReturn(run func(api.LoadLimit) error) *UCLPCServerInterface_SetConsumptionLimit_Call {
	_c.Call.Return(run)
	return _c
}

// SetContractualConsumptionNominalMax provides a mock function with given fields: value
func (_m *UCLPCServerInterface) SetContractualConsumptionNominalMax(value float64) error {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for SetContractualConsumptionNominalMax")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(float64) error); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UCLPCServerInterface_SetContractualConsumptionNominalMax_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContractualConsumptionNominalMax'
type UCLPCServerInterface_SetContractualConsumptionNominalMax_Call struct {
	*mock.Call
}

// SetContractualConsumptionNominalMax is a helper method to define mock.On call
//   - value float64
func (_e *UCLPCServerInterface_Expecter) SetContractualConsumptionNominalMax(value interface{}) *UCLPCServerInterface_SetContractualConsumptionNominalMax_Call {
	return &UCLPCServerInterface_SetContractualConsumptionNominalMax_Call{Call: _e.mock.On("SetContractualConsumptionNominalMax", value)}
}

func (_c *UCLPCServerInterface_SetContractualConsumptionNominalMax_Call) Run(run func(value float64)) *UCLPCServerInterface_SetContractualConsumptionNominalMax_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *UCLPCServerInterface_SetContractualConsumptionNominalMax_Call) Return(resultErr error) *UCLPCServerInterface_SetContractualConsumptionNominalMax_Call {
	_c.Call.Return(resultErr)
	return _c
}

func (_c *UCLPCServerInterface_SetContractualConsumptionNominalMax_Call) RunAndReturn(run func(float64) error) *UCLPCServerInterface_SetContractualConsumptionNominalMax_Call {
	_c.Call.Return(run)
	return _c
}

// SetFailsafeConsumptionActivePowerLimit provides a mock function with given fields: value, changeable
func (_m *UCLPCServerInterface) SetFailsafeConsumptionActivePowerLimit(value float64, changeable bool) error {
	ret := _m.Called(value, changeable)

	if len(ret) == 0 {
		panic("no return value specified for SetFailsafeConsumptionActivePowerLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(float64, bool) error); ok {
		r0 = rf(value, changeable)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFailsafeConsumptionActivePowerLimit'
type UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call struct {
	*mock.Call
}

// SetFailsafeConsumptionActivePowerLimit is a helper method to define mock.On call
//   - value float64
//   - changeable bool
func (_e *UCLPCServerInterface_Expecter) SetFailsafeConsumptionActivePowerLimit(value interface{}, changeable interface{}) *UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call {
	return &UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call{Call: _e.mock.On("SetFailsafeConsumptionActivePowerLimit", value, changeable)}
}

func (_c *UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call) Run(run func(value float64, changeable bool)) *UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(bool))
	})
	return _c
}

func (_c *UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call) Return(resultErr error) *UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call {
	_c.Call.Return(resultErr)
	return _c
}

func (_c *UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call) RunAndReturn(run func(float64, bool) error) *UCLPCServerInterface_SetFailsafeConsumptionActivePowerLimit_Call {
	_c.Call.Return(run)
	return _c
}

// SetFailsafeDurationMinimum provides a mock function with given fields: duration, changeable
func (_m *UCLPCServerInterface) SetFailsafeDurationMinimum(duration time.Duration, changeable bool) error {
	ret := _m.Called(duration, changeable)

	if len(ret) == 0 {
		panic("no return value specified for SetFailsafeDurationMinimum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Duration, bool) error); ok {
		r0 = rf(duration, changeable)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UCLPCServerInterface_SetFailsafeDurationMinimum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFailsafeDurationMinimum'
type UCLPCServerInterface_SetFailsafeDurationMinimum_Call struct {
	*mock.Call
}

// SetFailsafeDurationMinimum is a helper method to define mock.On call
//   - duration time.Duration
//   - changeable bool
func (_e *UCLPCServerInterface_Expecter) SetFailsafeDurationMinimum(duration interface{}, changeable interface{}) *UCLPCServerInterface_SetFailsafeDurationMinimum_Call {
	return &UCLPCServerInterface_SetFailsafeDurationMinimum_Call{Call: _e.mock.On("SetFailsafeDurationMinimum", duration, changeable)}
}

func (_c *UCLPCServerInterface_SetFailsafeDurationMinimum_Call) Run(run func(duration time.Duration, changeable bool)) *UCLPCServerInterface_SetFailsafeDurationMinimum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration), args[1].(bool))
	})
	return _c
}

func (_c *UCLPCServerInterface_SetFailsafeDurationMinimum_Call) Return(resultErr error) *UCLPCServerInterface_SetFailsafeDurationMinimum_Call {
	_c.Call.Return(resultErr)
	return _c
}

func (_c *UCLPCServerInterface_SetFailsafeDurationMinimum_Call) RunAndReturn(run func(time.Duration, bool) error) *UCLPCServerInterface_SetFailsafeDurationMinimum_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function with given fields: available
func (_m *UCLPCServerInterface) UpdateUseCaseAvailability(available bool) {
	_m.Called(available)
}

// UCLPCServerInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type UCLPCServerInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *UCLPCServerInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *UCLPCServerInterface_UpdateUseCaseAvailability_Call {
	return &UCLPCServerInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *UCLPCServerInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *UCLPCServerInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *UCLPCServerInterface_UpdateUseCaseAvailability_Call) Return() *UCLPCServerInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCLPCServerInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(bool)) *UCLPCServerInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// UseCaseName provides a mock function with given fields:
func (_m *UCLPCServerInterface) UseCaseName() model.UseCaseNameType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UseCaseName")
	}

	var r0 model.UseCaseNameType
	if rf, ok := ret.Get(0).(func() model.UseCaseNameType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.UseCaseNameType)
	}

	return r0
}

// UCLPCServerInterface_UseCaseName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseCaseName'
type UCLPCServerInterface_UseCaseName_Call struct {
	*mock.Call
}

// UseCaseName is a helper method to define mock.On call
func (_e *UCLPCServerInterface_Expecter) UseCaseName() *UCLPCServerInterface_UseCaseName_Call {
	return &UCLPCServerInterface_UseCaseName_Call{Call: _e.mock.On("UseCaseName")}
}

func (_c *UCLPCServerInterface_UseCaseName_Call) Run(run func()) *UCLPCServerInterface_UseCaseName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCLPCServerInterface_UseCaseName_Call) Return(_a0 model.UseCaseNameType) *UCLPCServerInterface_UseCaseName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCLPCServerInterface_UseCaseName_Call) RunAndReturn(run func() model.UseCaseNameType) *UCLPCServerInterface_UseCaseName_Call {
	_c.Call.Return(run)
	return _c
}

// NewUCLPCServerInterface creates a new instance of UCLPCServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUCLPCServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UCLPCServerInterface {
	mock := &UCLPCServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
