// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"

	model "github.com/enbility/spine-go/model"
)

// UCVABDInterface is an autogenerated mock type for the UCVABDInterface type
type UCVABDInterface struct {
	mock.Mock
}

type UCVABDInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *UCVABDInterface) EXPECT() *UCVABDInterface_Expecter {
	return &UCVABDInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function with given fields:
func (_m *UCVABDInterface) AddFeatures() {
	_m.Called()
}

// UCVABDInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type UCVABDInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *UCVABDInterface_Expecter) AddFeatures() *UCVABDInterface_AddFeatures_Call {
	return &UCVABDInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *UCVABDInterface_AddFeatures_Call) Run(run func()) *UCVABDInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCVABDInterface_AddFeatures_Call) Return() *UCVABDInterface_AddFeatures_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCVABDInterface_AddFeatures_Call) RunAndReturn(run func()) *UCVABDInterface_AddFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddUseCase provides a mock function with given fields:
func (_m *UCVABDInterface) AddUseCase() {
	_m.Called()
}

// UCVABDInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type UCVABDInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *UCVABDInterface_Expecter) AddUseCase() *UCVABDInterface_AddUseCase_Call {
	return &UCVABDInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *UCVABDInterface_AddUseCase_Call) Run(run func()) *UCVABDInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCVABDInterface_AddUseCase_Call) Return() *UCVABDInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCVABDInterface_AddUseCase_Call) RunAndReturn(run func()) *UCVABDInterface_AddUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnergyCharged provides a mock function with given fields: entity
func (_m *UCVABDInterface) EnergyCharged(entity api.EntityRemoteInterface) (float64, error) {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for EnergyCharged")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (float64, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) float64); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCVABDInterface_EnergyCharged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnergyCharged'
type UCVABDInterface_EnergyCharged_Call struct {
	*mock.Call
}

// EnergyCharged is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *UCVABDInterface_Expecter) EnergyCharged(entity interface{}) *UCVABDInterface_EnergyCharged_Call {
	return &UCVABDInterface_EnergyCharged_Call{Call: _e.mock.On("EnergyCharged", entity)}
}

func (_c *UCVABDInterface_EnergyCharged_Call) Run(run func(entity api.EntityRemoteInterface)) *UCVABDInterface_EnergyCharged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCVABDInterface_EnergyCharged_Call) Return(_a0 float64, _a1 error) *UCVABDInterface_EnergyCharged_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCVABDInterface_EnergyCharged_Call) RunAndReturn(run func(api.EntityRemoteInterface) (float64, error)) *UCVABDInterface_EnergyCharged_Call {
	_c.Call.Return(run)
	return _c
}

// EnergyDischarged provides a mock function with given fields: entity
func (_m *UCVABDInterface) EnergyDischarged(entity api.EntityRemoteInterface) (float64, error) {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for EnergyDischarged")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (float64, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) float64); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCVABDInterface_EnergyDischarged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnergyDischarged'
type UCVABDInterface_EnergyDischarged_Call struct {
	*mock.Call
}

// EnergyDischarged is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *UCVABDInterface_Expecter) EnergyDischarged(entity interface{}) *UCVABDInterface_EnergyDischarged_Call {
	return &UCVABDInterface_EnergyDischarged_Call{Call: _e.mock.On("EnergyDischarged", entity)}
}

func (_c *UCVABDInterface_EnergyDischarged_Call) Run(run func(entity api.EntityRemoteInterface)) *UCVABDInterface_EnergyDischarged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCVABDInterface_EnergyDischarged_Call) Return(_a0 float64, _a1 error) *UCVABDInterface_EnergyDischarged_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCVABDInterface_EnergyDischarged_Call) RunAndReturn(run func(api.EntityRemoteInterface) (float64, error)) *UCVABDInterface_EnergyDischarged_Call {
	_c.Call.Return(run)
	return _c
}

// IsUseCaseSupported provides a mock function with given fields: remoteEntity
func (_m *UCVABDInterface) IsUseCaseSupported(remoteEntity api.EntityRemoteInterface) (bool, error) {
	ret := _m.Called(remoteEntity)

	if len(ret) == 0 {
		panic("no return value specified for IsUseCaseSupported")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (bool, error)); ok {
		return rf(remoteEntity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) bool); ok {
		r0 = rf(remoteEntity)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(remoteEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCVABDInterface_IsUseCaseSupported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUseCaseSupported'
type UCVABDInterface_IsUseCaseSupported_Call struct {
	*mock.Call
}

// IsUseCaseSupported is a helper method to define mock.On call
//   - remoteEntity api.EntityRemoteInterface
func (_e *UCVABDInterface_Expecter) IsUseCaseSupported(remoteEntity interface{}) *UCVABDInterface_IsUseCaseSupported_Call {
	return &UCVABDInterface_IsUseCaseSupported_Call{Call: _e.mock.On("IsUseCaseSupported", remoteEntity)}
}

func (_c *UCVABDInterface_IsUseCaseSupported_Call) Run(run func(remoteEntity api.EntityRemoteInterface)) *UCVABDInterface_IsUseCaseSupported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCVABDInterface_IsUseCaseSupported_Call) Return(_a0 bool, _a1 error) *UCVABDInterface_IsUseCaseSupported_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCVABDInterface_IsUseCaseSupported_Call) RunAndReturn(run func(api.EntityRemoteInterface) (bool, error)) *UCVABDInterface_IsUseCaseSupported_Call {
	_c.Call.Return(run)
	return _c
}

// Power provides a mock function with given fields: entity
func (_m *UCVABDInterface) Power(entity api.EntityRemoteInterface) (float64, error) {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for Power")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (float64, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) float64); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCVABDInterface_Power_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Power'
type UCVABDInterface_Power_Call struct {
	*mock.Call
}

// Power is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *UCVABDInterface_Expecter) Power(entity interface{}) *UCVABDInterface_Power_Call {
	return &UCVABDInterface_Power_Call{Call: _e.mock.On("Power", entity)}
}

func (_c *UCVABDInterface_Power_Call) Run(run func(entity api.EntityRemoteInterface)) *UCVABDInterface_Power_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCVABDInterface_Power_Call) Return(_a0 float64, _a1 error) *UCVABDInterface_Power_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCVABDInterface_Power_Call) RunAndReturn(run func(api.EntityRemoteInterface) (float64, error)) *UCVABDInterface_Power_Call {
	_c.Call.Return(run)
	return _c
}

// StateOfCharge provides a mock function with given fields: entity
func (_m *UCVABDInterface) StateOfCharge(entity api.EntityRemoteInterface) (float64, error) {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for StateOfCharge")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) (float64, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(api.EntityRemoteInterface) float64); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UCVABDInterface_StateOfCharge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StateOfCharge'
type UCVABDInterface_StateOfCharge_Call struct {
	*mock.Call
}

// StateOfCharge is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *UCVABDInterface_Expecter) StateOfCharge(entity interface{}) *UCVABDInterface_StateOfCharge_Call {
	return &UCVABDInterface_StateOfCharge_Call{Call: _e.mock.On("StateOfCharge", entity)}
}

func (_c *UCVABDInterface_StateOfCharge_Call) Run(run func(entity api.EntityRemoteInterface)) *UCVABDInterface_StateOfCharge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EntityRemoteInterface))
	})
	return _c
}

func (_c *UCVABDInterface_StateOfCharge_Call) Return(_a0 float64, _a1 error) *UCVABDInterface_StateOfCharge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UCVABDInterface_StateOfCharge_Call) RunAndReturn(run func(api.EntityRemoteInterface) (float64, error)) *UCVABDInterface_StateOfCharge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function with given fields: available
func (_m *UCVABDInterface) UpdateUseCaseAvailability(available bool) {
	_m.Called(available)
}

// UCVABDInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type UCVABDInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *UCVABDInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *UCVABDInterface_UpdateUseCaseAvailability_Call {
	return &UCVABDInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *UCVABDInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *UCVABDInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *UCVABDInterface_UpdateUseCaseAvailability_Call) Return() *UCVABDInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *UCVABDInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(bool)) *UCVABDInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// UseCaseName provides a mock function with given fields:
func (_m *UCVABDInterface) UseCaseName() model.UseCaseNameType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UseCaseName")
	}

	var r0 model.UseCaseNameType
	if rf, ok := ret.Get(0).(func() model.UseCaseNameType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.UseCaseNameType)
	}

	return r0
}

// UCVABDInterface_UseCaseName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseCaseName'
type UCVABDInterface_UseCaseName_Call struct {
	*mock.Call
}

// UseCaseName is a helper method to define mock.On call
func (_e *UCVABDInterface_Expecter) UseCaseName() *UCVABDInterface_UseCaseName_Call {
	return &UCVABDInterface_UseCaseName_Call{Call: _e.mock.On("UseCaseName")}
}

func (_c *UCVABDInterface_UseCaseName_Call) Run(run func()) *UCVABDInterface_UseCaseName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UCVABDInterface_UseCaseName_Call) Return(_a0 model.UseCaseNameType) *UCVABDInterface_UseCaseName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UCVABDInterface_UseCaseName_Call) RunAndReturn(run func() model.UseCaseNameType) *UCVABDInterface_UseCaseName_Call {
	_c.Call.Return(run)
	return _c
}

// NewUCVABDInterface creates a new instance of UCVABDInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUCVABDInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UCVABDInterface {
	mock := &UCVABDInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
